######################################################################
# Automatically generated by qmake (3.1) Thu May 19 14:12:44 2022
######################################################################

TEMPLATE = app
TARGET = ex1
INCLUDEPATH += .
QT += widgets
Config += release

# Input
SOURCES += ex1.cpp
